/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Coordinates,
  PageCoordinates,
  Pageable,
} from '../models/index';
import {
    CoordinatesFromJSON,
    CoordinatesToJSON,
    PageCoordinatesFromJSON,
    PageCoordinatesToJSON,
    PageableFromJSON,
    PageableToJSON,
} from '../models/index';

export interface Create2Request {
    coordinates: Coordinates;
}

export interface Delete2Request {
    id: number;
}

export interface List2Request {
    pageable: Pageable;
}

export interface Read2Request {
    id: number;
}

/**
 * 
 */
export class CoordinatesControllerApi extends runtime.BaseAPI {

    /**
     */
    async create2Raw(requestParameters: Create2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Coordinates>> {
        if (requestParameters['coordinates'] == null) {
            throw new runtime.RequiredError(
                'coordinates',
                'Required parameter "coordinates" was null or undefined when calling create2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/coordinates`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CoordinatesToJSON(requestParameters['coordinates']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoordinatesFromJSON(jsonValue));
    }

    /**
     */
    async create2(requestParameters: Create2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Coordinates> {
        const response = await this.create2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delete2Raw(requestParameters: Delete2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delete2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/coordinates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async delete2(requestParameters: Delete2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.delete2Raw(requestParameters, initOverrides);
    }

    /**
     */
    async list2Raw(requestParameters: List2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageCoordinates>> {
        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling list2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/coordinates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageCoordinatesFromJSON(jsonValue));
    }

    /**
     */
    async list2(requestParameters: List2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageCoordinates> {
        const response = await this.list2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async read2Raw(requestParameters: Read2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Coordinates>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling read2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/coordinates/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoordinatesFromJSON(jsonValue));
    }

    /**
     */
    async read2(requestParameters: Read2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Coordinates> {
        const response = await this.read2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
