/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
    PersonToJSONTyped,
} from './Person';

/**
 * 
 * @export
 * @interface PagePerson
 */
export interface PagePerson {
    /**
     * 
     * @type {number}
     * @memberof PagePerson
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePerson
     */
    totalElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagePerson
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagePerson
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagePerson
     */
    size?: number;
    /**
     * 
     * @type {Array<Person>}
     * @memberof PagePerson
     */
    content?: Array<Person>;
    /**
     * 
     * @type {number}
     * @memberof PagePerson
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PagePerson
     */
    sort?: SortObject;
    /**
     * 
     * @type {PageableObject}
     * @memberof PagePerson
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PagePerson
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagePerson
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PagePerson interface.
 */
export function instanceOfPagePerson(value: object): value is PagePerson {
    return true;
}

export function PagePersonFromJSON(json: any): PagePerson {
    return PagePersonFromJSONTyped(json, false);
}

export function PagePersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePerson {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PersonFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PagePersonToJSON(json: any): PagePerson {
    return PagePersonToJSONTyped(json, false);
}

export function PagePersonToJSONTyped(value?: PagePerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PersonToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'pageable': PageableObjectToJSON(value['pageable']),
        'numberOfElements': value['numberOfElements'],
        'empty': value['empty'],
    };
}

