/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
    CoordinatesToJSONTyped,
} from './Coordinates';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    name: string;
    /**
     * 
     * @type {Coordinates}
     * @memberof Person
     */
    coordinates: Coordinates;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    creationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    eyeColor: PersonEyeColorEnum;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    hairColor?: PersonHairColorEnum;
    /**
     * 
     * @type {Location}
     * @memberof Person
     */
    location: Location;
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    height: number;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    nationality?: PersonNationalityEnum;
}


/**
 * @export
 */
export const PersonEyeColorEnum = {
    Green: 'GREEN',
    Orange: 'ORANGE',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;
export type PersonEyeColorEnum = typeof PersonEyeColorEnum[keyof typeof PersonEyeColorEnum];

/**
 * @export
 */
export const PersonHairColorEnum = {
    Green: 'GREEN',
    Orange: 'ORANGE',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;
export type PersonHairColorEnum = typeof PersonHairColorEnum[keyof typeof PersonHairColorEnum];

/**
 * @export
 */
export const PersonNationalityEnum = {
    UnitedKingdom: 'UNITED_KINGDOM',
    India: 'INDIA',
    Italy: 'ITALY',
    NorthKorea: 'NORTH_KOREA'
} as const;
export type PersonNationalityEnum = typeof PersonNationalityEnum[keyof typeof PersonNationalityEnum];


/**
 * Check if a given object implements the Person interface.
 */
export function instanceOfPerson(value: object): value is Person {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    if (!('eyeColor' in value) || value['eyeColor'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'coordinates': CoordinatesFromJSON(json['coordinates']),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'eyeColor': json['eyeColor'],
        'hairColor': json['hairColor'] == null ? undefined : json['hairColor'],
        'location': LocationFromJSON(json['location']),
        'height': json['height'],
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
    };
}

export function PersonToJSON(json: any): Person {
    return PersonToJSONTyped(json, false);
}

export function PersonToJSONTyped(value?: Person | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'coordinates': CoordinatesToJSON(value['coordinates']),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
        'eyeColor': value['eyeColor'],
        'hairColor': value['hairColor'],
        'location': LocationToJSON(value['location']),
        'height': value['height'],
        'nationality': value['nationality'],
    };
}

